### ISSUE TITLE
 Call to undefined function ElasticClient\config_path() 

### ISSUE THREAD

**Issue by gitzxd** [babenkoivan/elastic-migrations#1]
In ServiceProvider.php line 47: 
Call to undefined function ElasticClient\config_path() ?
how to fix?

**Comment by babenkoivan** [comment]
Hi @gitzxd, `config_path` is a built-in Laravel function. I need more data to analyze the problem.
What Laravel / PHP versions do you use? The package requires Laravel >= 6 and PHP >= 7.2

**Comment by gitzxd** [comment]
opps,I used laravel5.6

**Comment by gitzxd** [comment]
> Hi @gitzxd, `config_path` is a built-in Laravel function. I need more data to analyze the problem.
> What Laravel / PHP versions do you use? The package requires Laravel >= 6 and PHP >= 7.2

laravel5.6

**Comment by babenkoivan** [comment]
Sorry, but Laravel 5.x will not be supported. Please upgrade to Laravel 6 if you want to use the package.
