### ISSUE TITLE
Unable to import related model in index

### ISSUE THREAD

**Issue by laTruffe79** [babenkoivan/elastic-migrations#19]
| Software        | Version
| ------------- | ---------------
| PHP                | 7.4
| Elasticsearch | 7.9
| Laravel           | 8

**Describe the bug**
Hello, I'm unable to populate elasticsearch with a related model. In my example I'm indexing courses, every courses can have 1 or many keywords (belongstomany relation) all fields marked as searchableArray are indexed except the relation which should be a nested array. 
See the stackoverflow discussion please. I'm not the only one to have this problem, I don't know if it's a bug or a not well documented feature ? 
[https://stackoverflow.com/a/66018497/5794757](https://stackoverflow.com/a/66018497/5794757)

Thank you very much.

**Comment by babenkoivan** [comment]
Hey, I've answered on Medium, but I can see that you've already found a solution 🙂
