### ISSUE TITLE
Zero downtime migrations?

### ISSUE THREAD

**Issue by robigoal** [babenkoivan/elastic-migrations#21]
Is it possible to adjust the mapping of the fields in the index with this package? In an older package we used [scout-elasticsearch-driver#zero-downtime-migration](https://github.com/babenkoivan/scout-elasticsearch-driver#zero-downtime-migration) which created a new index with the new mapping, imported the data and changed the used alias if everything went fine.

Thanks for your great work!

Robert

**Comment by babenkoivan** [comment]
Hey @robigoal, I've decided not to include such feature out of the box, because it doesn't fit every project. Instead, I'll create a wiki page and describe how to create a zero-downtime migration. I'll work on it in the near future.

**Comment by babenkoivan** [comment]
Hi @robigoal, as promised here this [the guide](https://github.com/babenkoivan/elastic-migrations/wiki/Changing-Mapping-with-Zero-Downtime). I hope it will be helpful for you 🙂
