### ISSUE TITLE
Index::create not making use of Laravel scout prefix

### ISSUE THREAD

**Issue by chadidi** [babenkoivan/elastic-migrations#3]
Are you planning to add the prefix or we should do it manually in the migration! thanks

**Comment by babenkoivan** [comment]
Hi @chadidi, this is a standalone package, which is out of Scout boundaries.
I can't add Scout prefix support, but I can add a prefix configuration in this package as well.

Would it be helpful?

**Comment by chadidi** [comment]
Hey @babenkoivan, I done it with a helper function, and used it in the migrations and searchableAs in the model, but I still think this setting gonna be helpful especially for multi-tenant applications, thanks for your hard work love the package 📦 you made it so easy to use elasticsearch 💪

**Comment by babenkoivan** [comment]
Hey @chadidi, the index prefix name configuration has been added in [v1.1.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.1.0). Please publish the settings and configure it as needed.
