### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by ssayen** [babenkoivan/elastic-migrations#4]
Hi,

I'm tying to install your scout elasticsearch packages, but I'm stuck with an error on elastic-migrations :

```
composer require babenkoivan/elastic-migrations
Using version ^1.0 for babenkoivan/elastic-migrations
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing babenkoivan/elastic-adapter (v1.0.1) Loading from cache
  - Installing babenkoivan/elastic-client (v1.0.1) Loading from cache
  - Installing babenkoivan/elastic-migrations (v1.0.1) Loading from cache
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In MigrationStorage.php line 24:

  rtrim() expects parameter 1 to be string, null given  
                                                        

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

Looking at the code I guess I'm missing some conf item, 'elastic.migrations.storage_directory', but pretty new to Laravel I don't know how to workaround.

Thanks

**Comment by ssayen** [comment]
Hi, seems I found a workaround changing a bit `MigrationStorage.php` :

I replaced
```
$this->directory = rtrim(config('elastic.migrations.storage_directory'), '/');
```
By
```
$this->directory = rtrim(null !== config('elastic.migrations.storage_directory') ? config('elastic.migrations.storage_directory') : '', '/');
```

Now I can go on. But I guess it's an issue somehow.
Thanks

**Comment by babenkoivan** [comment]
Hi @ssayen, it's very likely, that you've cached the config file, which is not recommended on the development environment. Try to execute `php artisan cache:clear` and then reinstall the package.

I do not recommend to do any changes in the `vendors` directory as it's not safe (can be overwritten when you update the packages).

**Comment by ssayen** [comment]
Hi @babenkoivan you're right, even if I have no clue why config file is cached.
But it did the trick, thanks !

**Comment by r-nicol** [comment]
Just thought I would say I have had this issue on development and production. Deleting caches via artisan and by hand did not stop the error for me on `composer install`. The only "fix" that worked was to add @ssayen line of code, then run `composer install`. Once the command ran, without error, I change the line back and never get the error again. It might be worth another look I feel.

**Comment by sunnythewebdeveloper** [comment]
Running these commands creates the missing files 
("config/elastic.client.php", "config/elastic.migrations.php")
 and seems to resolves the issue.

php artisan vendor:publish --provider="ElasticClient\ServiceProvider"
php artisan vendor:publish --provider="ElasticMigrations\ServiceProvider"

Review following link for details 
https://github.com/babenkoivan/elastic-migrations
