### ISSUE TITLE
Zero Downtime Migration

### ISSUE THREAD

**Issue by ybert** [babenkoivan/elastic-migrations#41]
Hello @babenkoivan ,

In your old package for scout, you made an incredible work for zero downtime migration. I used it for years and it worked perfectly.
The good point was to start writing to new index with an alias with suffix _write while still searching in old index.

My re indexing is heavy and it can take hours.
With the new way you documented on this package, old index continue indexing new incoming documents. So when the import finished, we don't have these documents created by users in the new index.

I don't know how we can do it the old way (Indexing new documents to the new index while searching in the old, and then switch searching creating a new alias).
Do you know if this is possible ?

**Comment by babenkoivan** [comment]
Hey @ybert, thank you for the feedback! I need to update the documentation, it is now possible to use the `is_write_index` option when creating an alias to forward all writing operations to a specific index. I'll try it out and update the docs as soon as I finish with other tasks.

**Comment by codelinde** [comment]
@babenkoivan Thanks for pointing out the availability of the `is_write_index` option--I'm going to give this a shot myself 😸
