### ISSUE TITLE
Restart docker, index update document when using scout import

### ISSUE THREAD

**Issue by trannluongg** [babenkoivan/elastic-migrations#43]
I am running elasticsearch using docker. When I create the index with `php artisan elastic:migrate {x.php}`, then I run the command `php artisan scout:import {Model}`, when it's done, after a while I check the index there is no document. When I restart docker, the index is updated to document. Thanks

**Comment by babenkoivan** [comment]
Hey @trannluongg, it sounds like a problem with your setup and not the package itself. I can only recommend you to verify that your infrastructure meets the [package requirements](https://github.com/babenkoivan/elastic-migrations#compatibility) and carefully check `scout` and `elastic*` configurations.

**Comment by trannluongg** [comment]
@babenkoivan Thank you.
