### ISSUE TITLE
Support for Normalyzers

### ISSUE THREAD

**Issue by nw-mjl** [babenkoivan/elastic-migrations#50]
I might be missing it, but I do not see support for $settings->nomalizer. 
Is this the case? If so do you think it could be added?

**Comment by babenkoivan** [comment]
Hi @nw-mjl, 

`normalizer` belongs to the `analysis` section of index settings and can be defined as follows:

```php
$settings->analysis([
        'normalizer' => [
            'my_normalizer' => [
                'type' => 'custom',
                'char_filter' => [],
                'filter' => ['lowercase', 'asciifolding']
            ]
        ]
]);
```
