### ISSUE TITLE
`elastic:migrate:fresh` command doesn't work due to protections on index

### ISSUE THREAD

**Issue by stevebauman** [babenkoivan/elastic-migrations#57]
| Software        | Version
| ------------- | ---------------
| PHP                | 8.3
| Elasticsearch | 8.14.3
| Laravel           | 10.48.16

**Describe the bug**

Running `php artisan elastic:migrate:fresh` fails due to wildcard drops being disabled for safety by default in Elasticsearch 8.0:

https://www.elastic.co/guide/en/elasticsearch/reference/current/index-management-settings.html#action-destructive-requires-name

This protection can be disabled via the below:

```
PUT /_cluster/settings
{
  "transient": {
    "action.destructive_requires_name":true
  }
}
```

Though I think we can just update the command to loop through each index and delete them by name.

**To Reproduce**

```bash
php artisan elastic:migrate:fresh
```

```
Elastic\Elasticsearch\Exception\ClientResponseException 
400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Wildcard expressions or all indices are not allowed"}],"type":"illegal_argument_exception","reason":"Wildcard expressions or all indices are not allowed"},"status":400}
```

**Comment by ElvisIsKing666** [comment]
I certainly don't want PHP dropping all of my indices - only the ones I've created migrations for. I've hunted high and low and not found a command that can drop and reload a single index.

**Comment by stevebauman** [comment]
@ElvisIsKing666 this command is intentionally destructive and behaves exactly like the `php artisan migrate:fresh` command. Don't run it if you don't all your indicies dropped.

**Comment by ElvisIsKing666** [comment]
Thanks @stevebauman - what I meant was that when I run `artisan migrate:fresh` it doesn't try to drop all the DB's in my local mysql - just the one it manages. But I am assuming that the error for using '*' wildcards is letting me know that this module is trying to drop more than just the single index that is currently managed. I have not dug into the code to see how it's running the index deletion - but wildcards sound bad.

**Comment by stevebauman** [comment]
An index is the equivalent to a DB table:

- `artisan migrate:fresh` drops all DB tables
- `artisan elastic:migrate:fresh` drops all indexes

**Comment by ElvisIsKing666** [comment]
Interesting - I hadn't seen the analogy. I was thinking of elasticsearch as the DB engine - not as a single DB. I don't know much about elasticsearch yet - I've only really just started - so then it would be wise for me to partition my other indices - like APM and Logstash so that something like `migrate:fresh` can't affect them. I've not looked at how things are partitioned.

**Comment by babenkoivan** [comment]
Hi there, I think this has been raised before :) 

The main use case for `php artisan elastic:migrate:fresh` is to drop everything when running tests and it's okay to set `action.destructive_requires_name = false` on test environments. This is even mentioned in README:

> Note that this command uses wildcards to delete indices. This requires setting [action.destructive_requires_name](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-management-settings.html#action-destructive-requires-name) to false.

If you want to be safe or don't want to tweak index settings, you can always use `elastic:migrate:refresh`, which rolls back all migrations and then runs them again.

**Comment by ElvisIsKing666** [comment]
Right... I only just now understood this better. My 'elastic_migrations' table was NOT getting properly populated for some reason so elastic:migrate:refresh did not work properly. Once the table had the correct entries everything worked as documented. 

My apologies for not understanding the issue and the misleading comments
