### ISSUE TITLE
Support for unsigned_long Type in Elasticsearch Mapping

### ISSUE THREAD

**Issue by brfuat9** [babenkoivan/elastic-migrations#58]
While creating migrations, we often utilize the long type for numeric fields. However, it seems there is no unsigned_long type option available in the mapping configurations. This feature would be highly beneficial, especially for cases where we only deal with positive numeric values and need to maximize the range of values stored. Thanks.

https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

**Comment by babenkoivan** [comment]
Hey @brfuat9, thanks for the feature request!

I've added support in [elastic-adapter v4.1.0](https://github.com/babenkoivan/elastic-adapter/releases/tag/v4.1.0). Please update composer dependencies to apply the changes, and feel free to reopen this issue in case something doesn't work 🙂
