### ISSUE TITLE
elastic:migrate command conflicts with the elastic:migrate in babenkoivan/scout-elasticsearch-driver

### ISSUE THREAD

**Issue by kingkap** [babenkoivan/elastic-migrations#6]
After I installed `babenkoivan/elastic-migrations` and `babenkoivan/scout-elasticsearch-driver`, the 'php artisan elastic:migrate' command clashed

![image](https://user-images.githubusercontent.com/7274002/87714508-70f51b00-c7de-11ea-9a31-243add1c1bff.png)

**Comment by babenkoivan** [comment]
Hi @kingkap, I've just released [a new version](https://github.com/babenkoivan/scout-elasticsearch-driver/releases/tag/v4.2.2) of `scout-elasticsearch-driver` with a fix. I've renamed `elastic:migrate` command to `elastic:migrate-model`.
