### ISSUE TITLE
MIgration has hard coded table name

### ISSUE THREAD

**Issue by benperiton** [babenkoivan/elastic-migrations#7]
| Software        | Version
| ------------- | ---------------
| PHP                | 7.4.3
| Elasticsearch | 7.6.1
| Laravel           | 7.20

**Describe the bug**
The 'table' config option is not used in the migration file, so changing this value always results in "Migration table is not yet created"

**To Reproduce**
Change the 'table' config option to something other than elastic_migrations, run artisan migrate then run elastic:migrate

**Current behavior**
Results in "Migration table is not yet created"

**Expected behavior**
It should not return an error

**Comment by babenkoivan** [comment]
Hi @benperiton, thank you for reporting the bug!

It is fixed in [v1.2.1](https://github.com/babenkoivan/elastic-migrations/releases/tag/v1.2.1) 🎉
