### ISSUE TITLE
Keyword type definition

### ISSUE THREAD

**Issue by topstar199026** [babenkoivan/elastic-migrations#9]
https://www.elastic.co/guide/en/elasticsearch/reference/master/keyword.html

The keyword family includes the following field types:

keyword, which is used for structured content such as IDs, email addresses, hostnames, status codes, zip codes, or tags.
constant_keyword for keyword fields that always contain the same value.
wildcard, which optimizes log lines and similar keyword values for grep-like wildcard queries.

How to define in migration?

**Comment by babenkoivan** [comment]
@topstar199026 you can define them as follows:

```
$mapping->keyword('field_name');
$mapping->constantKeyword('field_name');
$mapping->wildcard('field_name');
```

I'll update `Mapping` docblock to reflect all available types.

**Comment by topstar199026** [comment]
Thanks for the reply.
![image](https://user-images.githubusercontent.com/56366160/94990297-f4403480-05b5-11eb-923d-dec0b28cec08.png)
can i change keywork's type to 'wildcard' ?

**Comment by babenkoivan** [comment]
It's not possible to update the field type in ES. You can only create a new field or drop the index and recreate it with the mapping you wish. 

If you are going to implement a full text search, I'd recommend to define it as `text`.
